{ self, inputs, ... }:
{
  flake.homeModules.i3 =
    {
      config,
      pkgs,
      lib,
      myopts,
      system,
      ...
    }:
    let
      monitors =
        if myopts.monitors == null then
          [
            {
              name = "none";
              config = "none";
            }
          ]
        else
          myopts.monitors;

      browser = if myopts.browser == null then "" else lib.getExe myopts.browser;
      brightnessctl = lib.getExe pkgs.brightnessctl;
      maim = lib.getExe pkgs.maim;
      xclip = lib.getExe pkgs.xclip;
      notifySend = lib.getExe pkgs.libnotify;
      hyprpicker = lib.getExe pkgs.hyprpicker;
      ncpamixer = lib.getExe pkgs.ncpamixer;
      btop = lib.getExe pkgs.btop;
      tesseract = lib.getExe pkgs.tesseract;
      pactl = "${pkgs.pulseaudio}/bin/pactl";
      nemo = lib.getExe pkgs.nemo;
      dunstExe = lib.getExe pkgs.dunst;

      screenshotDir = "${config.home.homeDirectory}/Pictures/Screenshots";

      scriptDefs = self.lib.wm-scripts {
        pkgs = pkgs;
        monitors = monitors;
        myopts = myopts;
      };

      tmuxInitScript = lib.getExe scriptDefs.tmuxInitScript;
      forceKillScript = lib.getExe scriptDefs.forceKillScript;

      monitorNames = map (m: m.name) monitors;

      # Bind workspaces 1-5 to screen 1 (primary), 6-10 to screen 2 (secondary)
      workspaceMonitorBinds =
        if myopts.monitors != null && builtins.length monitorNames >= 2 then
          let
            m0 = builtins.elemAt monitorNames 0;
            m1 = builtins.elemAt monitorNames 1;
          in
          ''
            workspace 1 output ${m0}
            workspace 2 output ${m0}
            workspace 3 output ${m0}
            workspace 4 output ${m0}
            workspace 5 output ${m0}
            workspace 6 output ${m1}
            workspace 7 output ${m1}
            workspace 8 output ${m1}
            workspace 9 output ${m1}
            workspace 10 output ${m1}
          ''
        else
          ''
            workspace 1 output primary
            workspace 2 output primary
            workspace 3 output primary
            workspace 4 output primary
            workspace 5 output primary
            workspace 6 output nonprimary
            workspace 7 output nonprimary
            workspace 8 output nonprimary
            workspace 9 output nonprimary
            workspace 10 output nonprimary
          '';

      i3ConfigContent = ''
        # ============================================================
        # i3 configuration — generated by Nix, do not edit manually
        # ============================================================

        set $mod Mod4

        # Font
        font pango:JetBrains Mono 10

        # Window appearance — no window titles, no borders, no gaps
        default_border pixel 0
        default_floating_border pixel 0
        for_window [class=".*"] border pixel 0
        gaps inner 0
        gaps outer 0
        smart_gaps on
        smart_borders on

        # Autostart
        exec --no-startup-id dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GTK_USE_PORTAL
        exec --no-startup-id ${dunstExe}
        exec --no-startup-id wpaperd
        exec --no-startup-id ${tmuxInitScript}

        # Terminal launches
        bindsym $mod+Return exec kitty -1
        bindsym $mod+Shift+Return exec kitty -1 -o background_opacity=0.4
        bindsym $mod+a exec kitty -1 --app-id fl ${ncpamixer}
        bindsym $mod+u exec kitty -1 --app-id fl ${btop}

        # App launches
        bindsym $mod+w workspace number $ws6; exec --no-startup-id sh -c "pgrep -i 'firefox|chromium|brave|floorp|zen|vivaldi' >/dev/null || ${browser}"
        bindsym $mod+Ctrl+w exec ${browser}
        bindsym $mod+t workspace number $ws1; exec --no-startup-id sh -c "pgrep -i 'telegram' >/dev/null || Telegram"
        bindsym $mod+e exec ${nemo} --class files
        bindsym $mod+Ctrl+p exec pear-desktop

        # Vicinae deeplinks
        bindsym $mod+d exec vicinae vicinae://toggle
        bindsym $mod+c exec vicinae vicinae://launch/clipboard/history
        bindsym $mod+space exec vicinae vicinae://launch/wm/switch-windows

        # Color picker
        bindsym F10 exec wl-copy $(${hyprpicker})

        # Wallpapers
        bindsym $mod+F6 exec wpaperctl next-wallpaper
        bindsym $mod+F4 exec wpaperctl previous-wallpaper

        # Screenshots & OCR
        bindsym Print exec --no-startup-id sh -c "${maim} -s | ${xclip} -selection clipboard -t image/png"
        bindsym $mod+Print exec --no-startup-id sh -c "mkdir -p '${screenshotDir}' && ${maim} '${screenshotDir}/screenshot_$(date +%Y%m%d_%H%M%S).png' && ${notifySend} -t 2000 'Screenshot Saved'"
        bindsym $mod+o exec --no-startup-id sh -c "${maim} -s | ${tesseract} stdin stdout | ${xclip} -selection clipboard"

        # Window control
        bindsym $mod+q kill
        bindsym $mod+Shift+q exec ${forceKillScript}
        bindsym $mod+v floating toggle
        bindsym $mod+f fullscreen toggle

        # System / Logout mode (Super+Escape)
        set $mode_system System: [e]xit | [s]hutdown | [r]eboot | [S]uspend | [h]ibernate
        mode "$mode_system" {
            bindsym e exec --no-startup-id i3-msg exit, mode "default"
            bindsym s exec --no-startup-id systemctl poweroff, mode "default"
            bindsym r exec --no-startup-id systemctl reboot, mode "default"
            bindsym Shift+s exec --no-startup-id systemctl suspend, mode "default"
            bindsym h exec --no-startup-id systemctl hibernate, mode "default"

            bindsym Return mode "default"
            bindsym Escape mode "default"
        }
        bindsym $mod+Escape mode "$mode_system"

        # Volume control
        bindsym XF86AudioRaiseVolume exec ${pactl} set-sink-volume @DEFAULT_SINK@ +10%
        bindsym XF86AudioLowerVolume exec ${pactl} set-sink-volume @DEFAULT_SINK@ -10%
        bindsym XF86AudioMute exec ${pactl} set-sink-mute @DEFAULT_SINK@ toggle
        bindsym $mod+KP_Up exec ${pactl} set-sink-volume @DEFAULT_SINK@ +10%
        bindsym $mod+KP_Down exec ${pactl} set-sink-volume @DEFAULT_SINK@ -10%
        bindsym $mod+KP_Begin exec ${pactl} set-sink-mute @DEFAULT_SINK@ toggle

        # Brightness control
        bindsym XF86MonBrightnessUp exec ${brightnessctl} set +10%
        bindsym XF86MonBrightnessDown exec ${brightnessctl} set 10%-

        # Focus movement
        bindsym $mod+Left focus left
        bindsym $mod+Right focus right
        bindsym $mod+Up focus up
        bindsym $mod+Down focus down
        bindsym $mod+h focus left
        bindsym $mod+l focus right
        bindsym $mod+k focus up
        bindsym $mod+j focus down

        # Move windows
        bindsym $mod+Shift+Left move left
        bindsym $mod+Shift+Right move right
        bindsym $mod+Shift+Up move up
        bindsym $mod+Shift+Down move down
        bindsym $mod+Shift+h move left
        bindsym $mod+Shift+l move right
        bindsym $mod+Shift+k move up
        bindsym $mod+Shift+j move down

        # Monitor movement
        bindsym $mod+Mod1+Left focus output left
        bindsym $mod+Mod1+Right focus output right
        bindsym $mod+Mod1+h focus output left
        bindsym $mod+Mod1+l focus output right
        bindsym $mod+Mod1+Shift+Left move container to output left
        bindsym $mod+Mod1+Shift+Right move container to output right
        bindsym $mod+Mod1+Shift+h move container to output left
        bindsym $mod+Mod1+Shift+l move container to output right

        # Layout switching
        bindsym $mod+Shift+e exec setxkbmap us
        bindsym $mod+Shift+u exec setxkbmap ua
        bindsym $mod+Shift+r exec setxkbmap ru
        bindsym $mod+Shift+p exec setxkbmap pl

        # Resize mode
        mode "resize" {
            bindsym Left resize shrink width 10 px or 10 ppt
            bindsym Down resize grow height 10 px or 10 ppt
            bindsym Up resize shrink height 10 px or 10 ppt
            bindsym Right resize grow width 10 px or 10 ppt
            bindsym h resize shrink width 10 px or 10 ppt
            bindsym j resize grow height 10 px or 10 ppt
            bindsym k resize shrink height 10 px or 10 ppt
            bindsym l resize grow width 10 px or 10 ppt

            bindsym Return mode "default"
            bindsym Escape mode "default"
            bindsym $mod+r mode "default"
        }
        bindsym $mod+r mode "resize"

        # Workspace monitor bindings (Workspaces 1-5 -> Screen 1, Workspaces 6-10 -> Screen 2)
        ${workspaceMonitorBinds}

        # Workspace definitions
        set $ws1 "1"
        set $ws2 "2"
        set $ws3 "3"
        set $ws4 "4"
        set $ws5 "5"
        set $ws6 "6"
        set $ws7 "7"
        set $ws8 "8"
        set $ws9 "9"
        set $ws10 "10"

        # Switch to workspace & launch assigned app if not running
        bindsym $mod+1 workspace number $ws1; exec --no-startup-id sh -c "pgrep -i 'telegram' >/dev/null || Telegram"
        bindsym $mod+2 workspace number $ws2; exec --no-startup-id sh -c "pgrep -i 'keepassxc' >/dev/null || keepassxc"
        bindsym $mod+3 workspace number $ws3; exec --no-startup-id sh -c "pgrep -i 'youtube_music|ytmdesktop' >/dev/null || ytmdesktop"
        bindsym $mod+4 workspace number $ws4; exec --no-startup-id sh -c "pgrep -i 'vesktop' >/dev/null || vesktop"
        bindsym $mod+5 workspace number $ws5; exec --no-startup-id sh -c "pgrep -i 'teams' >/dev/null || teams-for-linux"
        bindsym $mod+6 workspace number $ws6; exec --no-startup-id sh -c "pgrep -i 'firefox|chromium|brave|floorp|zen|vivaldi' >/dev/null || ${browser}"
        bindsym $mod+7 workspace number $ws7
        bindsym $mod+8 workspace number $ws8; exec --no-startup-id sh -c "pgrep -i 'steam' >/dev/null || steam"
        bindsym $mod+9 workspace number $ws9
        bindsym $mod+0 workspace number $ws10

        # Move focused container to workspace
        bindsym $mod+Shift+1 move container to workspace number $ws1
        bindsym $mod+Shift+2 move container to workspace number $ws2
        bindsym $mod+Shift+3 move container to workspace number $ws3
        bindsym $mod+Shift+4 move container to workspace number $ws4
        bindsym $mod+Shift+5 move container to workspace number $ws5
        bindsym $mod+Shift+6 move container to workspace number $ws6
        bindsym $mod+Shift+7 move container to workspace number $ws7
        bindsym $mod+Shift+8 move container to workspace number $ws8
        bindsym $mod+Shift+9 move container to workspace number $ws9
        bindsym $mod+Shift+0 move container to workspace number $ws10

        # Show workspace on current monitor (Super + Alt + 1..0)
        bindsym $mod+Mod1+1 workspace number $ws1; move workspace to output current
        bindsym $mod+Mod1+2 workspace number $ws2; move workspace to output current
        bindsym $mod+Mod1+3 workspace number $ws3; move workspace to output current
        bindsym $mod+Mod1+4 workspace number $ws4; move workspace to output current
        bindsym $mod+Mod1+5 workspace number $ws5; move workspace to output current
        bindsym $mod+Mod1+6 workspace number $ws6; move workspace to output current
        bindsym $mod+Mod1+7 workspace number $ws7; move workspace to output current
        bindsym $mod+Mod1+8 workspace number $ws8; move workspace to output current
        bindsym $mod+Mod1+9 workspace number $ws9; move workspace to output current
        bindsym $mod+Mod1+0 workspace number $ws10; move workspace to output current

        # Automatic application workspace rules
        for_window [class=".*[tT]elegram.*"] move to workspace number $ws1
        for_window [class=".*[kK]eepassxc.*"] move to workspace number $ws2
        for_window [class=".*(youtube_music|ytmdesktop).*"] move to workspace number $ws3
        for_window [class="^vesktop$"] move to workspace number $ws4
        for_window [class="^teams-for-linux$"] move to workspace number $ws5
        for_window [class=".*(firefox|chromium|brave|floorp|zen|vivaldi).*"] move to workspace number $ws6
        for_window [class="^steam$"] move to workspace number $ws8
        for_window [class="^steam_app_.*"] move to workspace number $ws9
        for_window [class="^mpv$"] move to workspace number $ws10

        # Floating window rules
        for_window [class="fl"] floating enable, resize set 95 ppt 95 ppt, move position center
        for_window [class="files"] floating enable, resize set 60 ppt 60 ppt, move position center

        # Full-screen terminal scratchpad
        for_window [class="terminal-scratch"] move to scratchpad, border pixel 0, resize set 100 ppt 100 ppt, move position 0 px 0 px
        bindsym $mod+s exec --no-startup-id sh -c "i3-msg '[class=\"terminal-scratch\"] scratchpad show' || kitty --class terminal-scratch tmux attach"

        # Toggle status bar visibility (Super+B)
        bindsym $mod+b bar mode toggle

        # Status bar without IP addresses (hidden/toggled off by default on startup, toggle with Super+B)
        bar {
            mode hide
            hidden_state hide
            modifier none
            status_command i3status
            position top
            colors {
                background #1a1a1a
                statusline #ffffff
                focused_workspace #c9b890 #c9b890 #000000
                active_workspace #333333 #333333 #ffffff
                inactive_workspace #1a1a1a #1a1a1a #888888
                urgent_workspace #ad401f #ad401f #ffffff
            }
        }
      '';

      i3StatusConfigContent = ''
        # i3status config — no IP addresses shown
        general {
            colors = true
            interval = 5
        }

        order += "volume master"
        order += "battery all"
        order += "cpu_usage"
        order += "memory"
        order += "tztime local"

        volume master {
            format = "♪: %volume"
            format_muted = "♪: muted"
            device = "default"
        }

        battery all {
            format = "%status %percentage"
        }

        cpu_usage {
            format = "CPU: %usage"
        }

        memory {
            format = "RAM: %used"
        }

        tztime local {
            format = "%Y-%m-%d %H:%M:%S"
        }
      '';

      dunstConfigContent = ''
        [global]
            font = JetBrains Mono 10
            corner_radius = 5
            width = (300, 450)
            height = 300
            offset = 15x15
            origin = top-right
            transparency = 10
            padding = 10
            horizontal_padding = 12
            frame_width = 2
            frame_color = "#c9b890"

        [urgency_low]
            background = "#1a1a1a"
            foreground = "#ffffff"
            timeout = 3

        [urgency_normal]
            background = "#1a1a1a"
            foreground = "#ffffff"
            timeout = 3

        [urgency_critical]
            background = "#ad401f"
            foreground = "#ffffff"
            frame_color = "#ad401f"
            timeout = 0
      '';
    in
    {
      services.poweralertd.enable = true;

      services.picom = {
        enable = true;
        backend = "glx";
        vSync = true;
        settings = {
          corner-radius = 5;
          shadow = false;
          fading = false;
          detect-rounded-corners = true;
          detect-client-opacity = true;
          use-damage = true;
        };
      };

      xdg.configFile."i3/config".text = i3ConfigContent;
      xdg.configFile."i3status/config".text = i3StatusConfigContent;
      xdg.configFile."dunst/dunstrc".text = dunstConfigContent;

      home.packages = with pkgs; [
        dmenu
        dunst
        pkgs.maim
        pkgs.xclip
      ];
    };
}
